export const LEERKANSEN_FETCH_LIST = 'LEERKANSEN_FETCH_LIST';
export const LEERKANSEN_FETCH_LIST_SUCCESS = 'LEERKANSEN_FETCH_LIST_SUCCESS';
export const LEERKANSEN_FETCH_LIST_FAILED = 'LEERKANSEN_FETCH_LIST_FAILED';

export function LeerkansenFetch() {
	return {
		type: LEERKANSEN_FETCH_LIST
	}
}
