export const LEERKANSEN_FETCH_LIST = 'LEERKANSEN_FETCH_LIST';
export const LEERKANSEN_FETCH_LIST_SUCCES = 'LEERKANSEN_FETCH_LIST_SUCCESS';
export const LEERKANSEN_FETCH_LIST_FAILED = 'LEERKANSEN_FETCH_LIST_FAILED';
export const LEERKANSEN_CREATE_ITEM = 'LEERKANSEN_CREATE_ITEM';
export const LEERKANSEN_CREATE_ITEM_SUCCES = 'gentlestuent/LEERKANSEN_CREATE_ITEM_SUCCESS';
export const LEERKANSEN_CREATE_ITEM_FAILED = 'gentlestuent/LEERKANSEN_CREATE_ITEM_FAILED';

// READ
export function LeerkansenFetch() {
	return {
		type: LEERKANSEN_FETCH_LIST
	}
}

// CREATE
export function LeerkansCreateItem(data) {
  return {
    type: LEERKANSEN_CREATE_ITEM,
    data
  };
}
